name: main-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dtrx-py/dtrx:2022-11-16
      options: "--user=root"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🛠️ Build
        run: |
          pip install build==0.7.0
          python3 -m build

      - uses: actions/upload-artifact@v2
        with:
          name: release-packages
          path: dist/
  test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dtrx-py/dtrx:2022-11-16
      # we need to be root for checkout to work without pain
      options: "--entrypoint='' --user=root"

    strategy:
      matrix:
        # py36 is currently broken disable it
        python: [py27, py37, py38, py39, py3.10, py3.11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🧪 Run Tox Tests
        run: |
          # switch to a non-root user; this is required for one of the dtrx
          # tests, which checks for an EACCESS error :/
          bash /entrypoint.sh bash -c \
            'sudo chown -R $(id -u):$(id -g) ${PWD} && TOX_ARGS="-e ${{ matrix.python }}" inv tox'

  test-missing-file-command:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: ✅ Test When `file` Command Not Present
        run: |
          pip install -r requirements.txt
          inv test-nonexistent-file-cmd

  manpage:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dtrx-py/dtrx:2022-11-16
      options: "--user=root"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: 📝 Generate Man Pages
        run: inv rst2man

      # upload-artifact to save the output wheels
      - uses: actions/upload-artifact@v2
        with:
          name: manpage-output
          path: dtrx.1

  windows:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🪟 Verify Windows Install Fails
        run: |
          pip install -r requirements.txt
          inv windows
