name: main-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 🛠️ Build
        run: |
          pip install build==0.7.0
          python -m build

      - uses: actions/upload-artifact@v2
        with:
          name: release-packages
          path: dist/
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python: [py27, py36, py37, py38, py39, py3.10]

    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: 🧪 Run Tox Tests
        run: TOX_ARGS='-e ${{ matrix.python }}' ./test.sh

  manpage:
    runs-on: ubuntu-20.04

    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: 📝 Generate Man Pages
        run: RUN_JOB=rst2man ./test.sh

      # upload-artifact to save the output wheels
      - uses: actions/upload-artifact@v2
        with:
          name: manpage-output
          path: dtrx.1
